---
title: "My English Activity Log M.E.AL"
author:
  - name: Dolinskii George
    url: {}
date: 09-16-2019
categories:
  - English activity
preview: 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


I often try to speak in english with my friends and with people around the world by "hello talks" app

october 25th : i starded listening the music with my friends and we tried to translate it french.

november 5th : i downloaded the "Hello talks" app. I speak in english with people around the world. It's very interesting because i meet new people and talk about everything. For example, i've discoved that there is "a dog day" at university in austria

november 12th : i downlaoded the "BBC News" app on my phone. I've starded watching videos (with subtitles) about marine biology on the train for 30min.

november 13th : i decided to change my device language into english. My smartphone and PS4 are configured in english

november 17th : i've watched videos (with subtitles) on youtube about the simpson series

december 7th  :i've watched a documentary about memory games (with subtitles) on Netflix. It is very interesting how a brain could quickly memorise a lot of things. The perception of memorise change my mind about it. I think that our memorise definite our personality. I saw that there are videos on youtube about the memorise ; it is a man (Nelson Dellis) that explain how to memorise something by techniques easily and quickly. I recommend to watch his videos.
