---
title: "article 7 : Here’s how climate change may make Australia’s wildfires more common"
description: |
  Extreme wildfires down under are linked to a weather pattern that starts in the Indian Ocean
author:
  - name: Dolinskii George
    url: {}
date: 02-23-2020
categories:
  - wildfires
preview: https://www.sciencenews.org/wp-content/uploads/2020/01/010820_CG_wildfire_QA_feat-1028x579.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Source

ScienceNews [https://www.sciencenews.org/article/how-climate-change-may-make-australia-wildfires-more-common]

## Vocabulary

|  words from the text | synonym/explanation in english                                      |
| -------------------- | ------------------------------------------------------------------- |
| raging               | happening with a lot of force or violence                           |
| drought              | a long period of time when there is little or no rain and crops die |
| moisture             | a small amount of water or another liquid in the air                |
| blaze                | fire                                                                |
| culprit              | cause                                                               |
| outlook              | predict                                                             |
| flooding             | inundation                                                          |
| landslide            | mudslide                                                            |
| bushfires            | wildfires                                                           |
|  haze                | fog                                                                 |
| threefold            | triple                                                              |
| substed              | decreased                                                           |
| substantial          | considerable                                                        |

## Analysis table

|                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ------------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Researchers        | Wenju Cai a climate scientist of CSIRO  in Melbourne, Australia.                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| Published in       | January 9, 2020 AT 12:17 PM                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| General topic      | Extreme wildfires could linked to a weather pattern. it fueled by long-term drought and extreme heat, were exacerbated by a weather pattern known as the Indian Ocean dipole.                                                                                                                                                                                                                                                                                                                                                    |
| Procedure          | for years, Australia's fire managers have kept an eye on one cause that's behind hot, dry years in eastern Australia and that may be affected by global warming : this is an oscillating El Nino-like ocean-atmosphere wheather pattern. this El-nino pattern has positive, negative and neutral phases. it is depending on whether eastern or western Indian Ocean waters are warmer than average. So, if it's a strong positive phase, it correlates to some of Australia’s worst fire season says climate scientist Wenju Cai |
| Conclusion         | under global warming, that kind of huge Indian Ocean dipole will increase threefold by 2100. the dipole would change if temperatures are stabilized at 1.5 to 2 degrees celsius. The good news is that really cutting greenhouse gas emission effective and it stabilizes the dipole.                                                                                                                                                                                                                                            |
| remaining question | /                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
