---
title: " article 5 : Wasps are shrinking in size and it may be because of climate change"
author:
  - name: Dolinskii George
    url: {}
date: 12-11-2019
categories:
  - wasps
preview: https://pbs.twimg.com/media/EA_sKLEWwAAAnK5.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Source

NewScientist [https://www.newscientist.com/article/2212024-wasps-are-shrinking-in-size-and-it-may-be-because-of-climate-change/]

## Vocabulary

words from the text  | synonym/explanation in english
------------- | -------------
shrink  | to become smaller in size
ongoing  | still happening
sparrow  | a small brown bird
poorly  | badly
over time  | with time
tied  | linked
speed up  | accelerate
handful  | minor
hive  | a container in which bees live and make honey
hunt  | to kill animals for food

## Analysis table

  | 
------------- | -------------
Researchers  | Carlo Polidori (an entomologist) at the university fo Castilla (in spain) and his colleagues 
Published in  | 1st august 2019
General topic  | Wasps species appears to be shrinking as a consequence of global rise in temperatures caused by climate change.
Procedure  | The team had an opportunity to measure the body size, head width, and wing size of over 200 tree wasps (Dolichovespula sylvestris) at Madrid's National Museum of natural Sciences. They saw how insects bodies have changed ove time. These specimens came from various locations on the Iberian Peninsula, and some dated back to as early as 1904.
Conclusion  | They found that the wasps got smaller over time. Comparing their data with Iberian climate records, they found that this decline in size correlated with rising temperatures. shrinking in insects may be tied to their early development, which speeds up in hotter temperatures and can produce smaller adults. But it is not certain because environmental factors other than temperature may be the direct driver of wasp shrinkage.
Remaining question  | /


