---
title: "article 6 : Climate change may be why birds are migrating earlier across the United States"
description: |
  Birds are migrating earlier in recent decades, which could disrupt feeding and nesting cycles
author:
  - name: Dolinskii George
    url: {}
date: 02-09-2020
categories:
  - Birds
preview: https://www.sciencenews.org/wp-content/uploads/2019/12/121319_sb_bird-migration_feat-1028x579.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Source

ScienceNews [https://www.sciencenews.org/article/climate-change-why-birds-are-migrating-earlier-across-united-states]

## Vocabulary

| words from the text |  synonym/explanation in english                                                      |
| ------------------- | ------------------------------------------------------------------------------------ |
| to nest             | if a bird nests, it builds or uses a nest, especially to keep its eggs and babies in |
| a broad             | a wide                                                                               |
| fall night          | autumn night                                                                         |
| breadth             | the distance from one side of an object to the other                                 |
| encompass           | to include a lot of people or things                                                 |
| overhead            | above your head                                                                      |
| trend               | effect                                                                               |
| toward              | advancing                                                                            |
| weak                | low                                                                                  |
| grounded by         | stopped by                                                                           |
| out of whack        | not working normally                                                                 |
| breeding ground     | a place where animals reproduce                                                      |
| to starve           | to suffer or to die because there is not enough food                                 |
| dwindle             | to become gradually less                                                             |

## Analysis table

|                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| ------------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Researchers        | Andrew Farnsworth, a migration ecologist at Cornell University                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| Published in       | December 17, 2019                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| General topic      | Recent studies have shown that some birds are migrating earlier in the recent decade ,  it can cause a problem especially to nesting and feeding cycle.                                                                                                                                                                                                                                                                                                                                                        |
| Procedure          | Farnsworth and his colleagues collected data from 13 million radar scans taken on 2,115 spring nights and 2,152 fall nights by 143 weather surveillance stations across the continental United States from 1995 to 2018. there are Groups of migrating birds show up as circular blobs. The researchers couldn’t identify specific species from the radar blobs but their analysis included hundreds of species.                                                                                               |
| Conclusion         | The researchers found that, in the spring, birds migrated half a day earlier on average each decade. The trend is weaker in fall, birds departures south are often grounded by rainstorms and young birds are added to the migration mix. Therefore, birds may arrive before the spike in insect populations and it could be a several problem to eat because young birds might starve. By contrast, The researchers didn’t see a strong link between changing temperatures and migration timing in the fall.  |
| Remaining question | /                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |

