---
title: "article 4 : impact of climate change on global banana yields relevead"
author:
  - name: Dolinskii George
    url: {}
date: 11-29-2019
categories:
  - banana
preview: https://img-aws.ehowcdn.com/350x235p/s3-us-west-1.amazonaws.com/contentlab.studiod/getty/40c8dd09bee74cd18de4e3a9f375ae80.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Source

ScienceDaily [https://www.sciencedaily.com/releases/2019/09/190902113623.htm]

## Vocabulary

| words from the text | synonym/explanation in english                                                             |
| ------------------- | ------------------------------------------------------------------------------------------ |
| yield               | to produce fruit                                                                           |
| crop                | a plant grown for food                                                                     |
| income              | money that someone gets from investing money                                               |
| highlight           | underline                                                                                  |
| wilt                | if a plant wilts, it gradually bends towards the ground because it needs water or is dying |
| trade               | commerce, business                                                                         |
| commodity           | something that can be bought and sold, especially a basic food product                     |
| to ensure           | to provide                                                                                 |
| to assess           | to evaluate                                                                                |
| trend               | effect, change                                                                             |
| to scatter          | to spread, to disperse                                                                     |
| counteract          | to reduce the negative effect of something by doing something that has an opposite effect  |

## Analysis table

|                     |                                                                                                                                                                                                                                                                                                                                                                                  |
| ------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Researchers         | Dr Dan Bebber (a Senior Lecturer in Biosciences) from the University of Exeter                                                                                                                                                                                                                                                                                                   |
| Published in        | September 2, 2019                                                                                                                                                                                                                                                                                                                                                                |
| General topic       | Climate change could negatively impact banana cultivation in some of the world's most important producing and exporting countries                                                                                                                                                                                                                                                |
| Procedure           |  there are many reports have looked at the impact of climate change on agricultural production. scientists have studied both the recent and future impact of climate change on the world's leading banana producers and exporters. The reports suggests that banana production could be significantly reduced, or disappear, by 2050 if climate change continues at its expected |
| Remaining questions | It is imperative  that to invest in preparing tropical agriculture for future climate change. Scientists believe practical solutions exist, but these are scattered needs across banana producing countries.                                                                                                                                                                     |
