---
title: "article 8 : What is climate change, and how is it affecting Earth ? "
description: |
  Climate change is any long-term alteration in average weather patterns.
author:
  - name: Dolinskii George
    url: {}
date: 03-14-2020
categories:
  greenhouse gases
preview: https://cdn.mos.cms.futurecdn.net/m7bQd3TJ6wDCnmHyzkTtmc-650-80.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Source

LiveScience [https://www.livescience.com/climate-change.html]

## Vocabulary

| Words from the text | synonym/explanation in english                                          |
| ------------------- | ----------------------------------------------------------------------- |
| Flow                | rate                                                                    |
| thrive              | prosper                                                                 |
| blur                | it becomes difficult to see it clearly                                  |
| chock-full          | very full, especially with things that are pleasant or enjoyable        |
| ash                 | the grey powder that remains after something has burned                 |
| wealth              | fortune                                                                 |
| coverage            | the amount and type of protection that an insurance agreement gives you |
| swift               | quickly                                                                 |
| shell               | the hard outer part that protects the body of a sea creature            |
| forestall           | prevent                                                                 |

## Analysis table

|                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Researchers        |  Ellen Mosley-Thompson, a paleoclimatologist at the Byrd Polar and Climate Research Center of The Ohio State University. Kathie Dello, North Carolina's state climatologist. Josef Werne, a geochemist and paleoclimatologist at the University of Pittsburgh                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| Published in       | March 10, 2020                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| General topic      | climate change has occurred many times in Earth's history, and for many reasons. The changes in global temperature and weather patterns. Major problems are caused by the human activity. They are happening much faster than the natural climate variations of the past                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Procedure          | Scientists have many ways to track climate. climate change is linked to the emission of greenhouse gases such as carbon or methane. these gases trap heat from the sun's rays near earth's surface. small changes in the proportions of greenhouse gases in the air can add up to major change on a global scale. Scientists can record climate change of the past in ice, sediments, cave formations,coral reefs and even tree rings, for example they can measure tree rings to get a season-by-season record of temperature and moisture. Different type of natural records have different strengths. Ocean sediments can provide blurrier pictures of climate dating back millions of years. The most recent changes in the climate  is since the beginning of the Industrial Revolution.  The advent of satellite technology in the 1970s  has provided an explosion of data. Melting ice and the expansion of ocean waters due to heat have already contributed to sea level rise. ocean water absorbs carbon dioxide from the atmosphere which creates a chemical reaction that causes ocean acidification. Global average pH of ocean surface waters has decreased by 0.11 since the Industrial Revolution began, a 30% increase in acidity.  |
| conclusion         | if all human greenhouse gas emissions stopped, earth would likely still experience more warming, because carbon dioxide remains in the atmosphere for hundreds of years. There are projects that could theoretically reverse some of this problem to warming by removing carbon dioxide from atmosphere, such as carbon capture and storage, which involves injecting carbon into underground reservoirs. Advocates argue that carbon capture and storage is technologically feasible.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| remaining question | /                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
